# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:57
from __future__ import unicode_literals

import os

from django.db import connection, migrations

def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), '../sql/', filename)
    sql_statement = open(file_path).read()
    print(sql_statement)
    with connection.cursor() as c:
        c.execute(sql_statement)

initial_schema = lambda x,y: load_data_from_sql('final_schema.sql')
initial_value = lambda x,y: load_data_from_sql('data_set.sql')

class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_schema),
        # migrations.RunPython(initial_value),
    ]
